### ISSUE TITLE
[Feature Request] Create a title page and link back to fiction page

### ISSUE THREAD

**Issue by kekkoudesu** [Aivean/royalroad-downloader#30]
It would be useful to generate a title page with these details:

* Link to the work on Royal Road
* Title
* Author name
* Datetime the work was scraped

I mostly just wanted a link to get back to the fiction page.

**Comment by Aivean** [comment]
Implemented in https://github.com/Aivean/royalroad-downloader/releases/tag/v2.10.0

**Comment by ZeeWanderer** [comment]
The title page section needs `chapter` class like in #22 to appear in ToC post-conversion to epub. Changing "title" class to "chapter" sort of works, but because title and description are divided by 2 distinct `h1`/`h2` tags they are treated as separate chapters.
The chapter name is whatever in the `h1`/`h2` tags. Maybe a good idea to instead put `Title` into the first `h1` tag and make `a` link and image a paragraph content and then the same thing for description.

Something like this for the title
```html
          <h1 class="chapter">
            Title
          </h1> <!-- link back to the fiction page -->
          <a href="https://www.royalroad.com/fiction/86267">
            [Farmer] Mage | Royal Road
          </a>
          <be> <!-- needed -->
          <img class
```
and
```html
          <h1 class="chapter">
              Description
          </h1>
          <h3>by
            S.C. King
```
for description
so that it looks like this 
![image](https://github.com/Aivean/royalroad-downloader/assets/8377469/ada28333-9698-4180-88a6-d765ec091389)
![image](https://github.com/Aivean/royalroad-downloader/assets/8377469/8b8230dd-50af-4b1a-ab8b-96d8e9eccc79)

**Comment by Aivean** [comment]
@ZeeWanderer, why do you you need a separate ToC item for the title, if it's the first page of the book?

**Comment by ZeeWanderer** [comment]
Hhhhhhm, i can't really answer that question coherently. I guess for feature completeness and because it usually is that way. If it's a separate "section" its supposed to be indexed. On the other hand some publishers do leave out the title page, but index the rest.
![image](https://github.com/Aivean/royalroad-downloader/assets/8377469/669e238f-8773-4ca3-972a-68594e688f46)
![image](https://github.com/Aivean/royalroad-downloader/assets/8377469/214a52e1-dd15-4da3-8b1a-906a2de7505e)

I suppose its not truly needed or required so - sorry for the disturbance.

**Comment by Aivean** [comment]
@ZeeWanderer, I have objection for marking title page with the `chapter` class — semantically it's not a chapter. If you find an alternative method that is supported by your converter, PR would be welcome.
